### ISSUE TITLE
CutoutPercentage in ChartJS3 doesn't seem to be working

### ISSUE THREAD

**Issue by Terricide** [iceteagroup/wisej-extensions#77]
It always is stuck at the default of 50%, I can't seem to change it to anything else. This works in the ChartJS library.

**Comment by LRufenacht** [comment]
Thanks for letting us know.

It looks like cutoutpercentage was renamed to cutout in ChartJS 3.

I pushed a new NuGet build that should be available within a few minutes (2.5.21): https://www.nuget.org/packages/Wisej-2-ChartJS3/

Please let me know if it works.

Regards,
Levie

**Comment by Terricide** [comment]
It seems to be fixed now :)

**Comment by Terricide** [comment]
Can the cutout be changed to a string?

https://www.chartjs.org/docs/latest/charts/doughnut.html

Looking over the documentation cutout as a number equals pixels but if it is 90% as a string then it is a percentage.

**Comment by Terricide** [comment]
I saw you pulled the fix, are you going to publish a new version to nuget?

**Comment by LRufenacht** [comment]
Hi Terricide,
The NuGet should be updated now.
Thanks,
Levie

**Comment by Terricide** [comment]
Cool thanks,

Also https://www.chartjs.org/docs/latest/getting-started/v3-migration.html
HorizontalBar has been depreciated and there is a new way to do that bar.
