### ISSUE TITLE
ColumnFilter exception due to missing Messages.resource file

### ISSUE THREAD

**Issue by iuliapitutiu** [iceteagroup/wisej-extensions#80]
Hi,

For the Aareon project, I need to extend the Column Filtering in order to support an advanced filtering where user can select either Simple or Where Column filter (I was thinking to have a Tab Control with a page for Simple column filter, the other with Where filtering). Therefore I need to re-use the Ext.ColumnFilter code but I get an exception due to missing resource file. Please see my attached printscreen.
![ColumnFilter](https://user-images.githubusercontent.com/66007459/150303360-bf2d9f7c-0cdb-4563-95b2-02e2fb826187.PNG)
 
Thanks
Iulia

**Comment by FrankITG** [comment]
Hi Iulia,
thanks for reporting this. I´ll take a look and get back to you.

Best regards
Frank

**Comment by iuliapitutiu** [comment]
Hi Frank,

One more detail I noticed: System.Linq is now deprecated and when updating it to System.Linq.Dynamic.Core, the Where filter would require an update of the Linq predicate.

Best regards
Iulia

**Comment by FrankITG** [comment]
Hi Iulia,

I updated here in GitHub and added the missing resources and will also add it to the nuget package for the next update.
I´ll check what you wrote about System.Linq and get back to you.

Best regards
Frank

**Comment by iuliapitutiu** [comment]
Hi Frank

I was wondering if there are any news on the Linq topic and when we can expect an update there. We need to finalize this filtering feature for our customer.

Thank you for your understanding
Iulia

**Comment by FrankITG** [comment]
Hi Iulia,
I´ll work on it this weekend and keep you updated.

Best regards
Frank

**Comment by FrankITG** [comment]
Hi Iulia,

I fixed some issues with the localization, linked to System.Linq.Dynamic.Core package and also added a RowsFiltered event that you can use to determine when filtering is done and also retrieve the number of currently displayed rows.
Nuget package will be updated with the next Wisej release.

Best regards
Frank

**Comment by iuliapitutiu** [comment]
Hi Frank,

That's great news - thanks. Could you also commit the code? For Aareon, we cannot use the Wisej extension AS IS, we will have to re-use the code and adjust it to support the Filter Builder and column filter together, something like here:
https://js.devexpress.com/Demos/WidgetsGallery/Demo/DataGrid/FilterPanel/Angular/Light/

Thanks & have a nice weekend
Iulia

**Comment by FrankITG** [comment]
Hi Iulia,
it should be online now.

Best regards
Frank

**Comment by iuliapitutiu** [comment]
Hi Frank,

I have checked the changes, but as far as I can see, System.Linq.Dynamic.Core package is referenced in the project, but still the old System.Linq library is used (this is also referenced from \lib folder and it is used in the code).

Could you please check it again?

Thanks
Iulia
