### ISSUE TITLE
Wisej.Ext.FontAwesome Stacking Support wisej-js

### ISSUE THREAD

**Issue by skeller1** [iceteagroup/wisej-extensions#81]
Hello,
we are searching for a proper solution to support Font Awesome Stacking in all controls with image source functionalitity.

https://fontawesome.com/docs/web/style/stack

It would be very nice to select 2 icons as properties in the designer, change position of the layered icons and get a merged icon in the designer /html output.

What would be the correct way to reach this goal? Extenders?

Thanks skeller1

**Comment by LRufenacht** [comment]
Hi Skeller1,

Your best bet is to use an SVG merger like this: https://products.aspose.app/words/merger/svg

Unfortunately we don't support merging SVGs in Visual Studio for the time being.

Best,
Levie

**Comment by lucapivato** [comment]
You can also place 2+ images over each other. Like the font awesome link does. Two PictureBox for example. Or you can simply create a custom extended class and put as many images as you like.

![image](https://user-images.githubusercontent.com/37640802/212353115-f7e6f60b-4c70-4495-9d78-df11d182cea5.png)

![image](https://user-images.githubusercontent.com/37640802/212353233-a7a26717-c395-4db7-9e69-264a2acb8e37.png)

```
	public class TwoImageButton : Button
	{
		PictureBox _image2;

		public TwoImageButton()
		{
			_image2 = new PictureBox {
				Parent = this,
				Size = new System.Drawing.Size(20, 20),
				Anchor = AnchorStyles.Left,
				Location = new System.Drawing.Point(10, (this.Height - 20) / 2)
			};
		}

		[TypeConverter("Wisej.Design.ImageSourceConverter, Wisej.Framework.Design, Version=3.0.0.0, Culture=neutral, PublicKeyToken=17bef35e11b84171")]
		[Editor("Wisej.Design.ImageSourceEditor, Wisej.Framework.Design, Version=3.0.0.0, Culture=neutral, PublicKeyToken=17bef35e11b84171",
				"System.Drawing.Design.UITypeEditor, System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a")]
		public string ImageSource2
		{
			get => _image2.ImageSource;
			set => _image2.ImageSource = value;
		}
	}
```

This is just a sample, the location, size, adjustments, have to be thought of and planned depending on the requirements.

Another option would be to use a custom URL and process the images on the server in an api call. But you wouldn't be able to use the designer for the images in that case.

**Comment by LRufenacht** [comment]
Closing. Feel free to reopen if additional information is needed.

**Comment by skeller1** [comment]
Thank you for the idea with the custom button class. We decided to build the custom icons in external tools (Indesign, SVG Merge Tools,...).

After that we will add this icon to our own Wisej.Ext.FontAweseome* Nuget Package.

Thank you
