### ISSUE TITLE
Please fix compiler error: GeMnemonic

### ISSUE THREAD

**Issue by jenssd** [iceteagroup/wisej-extensions#83]
Hi, project is not compilable.
Please fix compiler error in RibbonBarPage.cs.

![image](https://user-images.githubusercontent.com/18581034/223074579-bd972768-470c-4a39-88b5-4c225ad31ac6.png)

Creating a Pull Reqeust was not possible (Remote: Permission to iceteagroup/wisej-extensions.git denied)

Best,
Jens

**Comment by AlaaTrAce** [comment]
Hi Jens, 

I have pushed an update to the GitHub repo just now!

Best,
Alaa
