### ISSUE TITLE
NavigationBar compact view issue

### ISSUE THREAD

**Issue by abradea** [iceteagroup/wisej-extensions#86]
When the NavigationBar is displayed in compact view, if there is a long list of subitems, not all of them are displayed and there is no way to scroll.
[NavigationCompactView.zip](https://github.com/iceteagroup/wisej-extensions/files/11078286/NavigationCompactView.zip)

**Comment by AlaaTrAce** [comment]
Hi Andrea,

Thank you for reporting the issue, we have taken note of it and we'll inform you when a fix is available!

Best,
Alaa

**Comment by lucapivato** [comment]
Workaround:

```

			this.InitScript = @"
				qx.Class.define('wisej.web.ext.NavigationBarMenu', {

					extend: wisej.web.menu.ContextMenu,

					properties:{
						appearance:{init:'navbar-menu', refine:true}
					}
				});";

```

You can scroll using the wheel. If you want to show the scroller buttons you need this in the theme or mixin

```
"menu": {
    "inherit":"menu",
    "components":{
         "slidebar":{
             "inherit":"slidebar"
         }
    }
}

```

![image](https://user-images.githubusercontent.com/37640802/228944153-97f318f8-93f1-4d7b-95ea-5e1417ce816c.png)
