### ISSUE TITLE
ColumnFilter - sorting resets the filter

### ISSUE THREAD

**Issue by abradea** [iceteagroup/wisej-extensions#87]
If you a filter a column and then sort another one, the filter from the 1st column is reset.
[SortColumnFiltering.zip](https://github.com/iceteagroup/wisej-extensions/files/11119380/SortColumnFiltering.zip)

**Comment by FrankITG** [comment]
@abradea This is fixed in 3.1.10 and will also be included in 3.2.  
Please reopen in case of any issues.
