### ISSUE TITLE
Wisej-Web.Ext.Columnfilter version conflict warning

### ISSUE THREAD

**Issue by skeller1** [iceteagroup/wisej-extensions#89]
Hi,

we want to use Wisej 3 Web Ext Columnfilter in our migration project (net48). But we got the warning that there is a version conflict with System.Linq.Dynamic.Core (1.2.0.0 vs 1.2.15.0)

```
  C:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.target
s(2352,5): warning MSB3277: Es wurden Konflikte zwischen verschiedenen Versionen von "System.Linq.Dynamic.Core" gefunde
n, die nicht aufgelöst werden konnten. []
C:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(
2352,5): warning MSB3277: Konflikt zwischen System.Linq.Dynamic.Core, Version=1.2.0.0, Culture=neutral, PublicKeyToken=
0f07ec44de6ac832 und System.Linq.Dynamic.Core, Version=1.2.15.0, Culture=neutral, PublicKeyToken=0f07ec44de6ac832. []
```

So we started to build our own nuget version of this package using the latest 3.1 branch and local nuget file feed.

As a result the nuget package manager lists different minimal versions for System.Linq.Dynamic.Core

## Nuget dependencies official nuget package
![image](https://user-images.githubusercontent.com/226753/233907782-ee8261c0-a7bb-4db7-9454-fe058311e2a0.png)

## Nuget dependencies of our local nuget package
![image](https://user-images.githubusercontent.com/226753/233907313-c12836ea-13d1-4b3d-80b4-716264f31d7a.png)

Could this be a problem of the building process? Our any adice to fix this warning in our project?

Thank you

**Comment by AlaaTrAce** [comment]
Hi @skeller1 ,

You can fix the conflict by directly adding the dependency package from NuGet.
Instead of using the versions shown in the dependencies of your other packages, Visual Studio will utilize the version of the package that is explicitly referenced.

HTH,
Alaa

**Comment by skeller1** [comment]
Hi @AlaaTrAce,

thank you for your explanations. But there is something that I don`t understand:

The Column Filter Project is referencing System.Linq.Dynamic.Core 1.2.15 (https://github.com/iceteagroup/wisej-extensions/blob/c8dddf78b8bb41d9e1336d21c86a142b1026901b/Wisej.Web.Ext.ColumnFilter/Wisej.Web.Ext.ColumnFilter.csproj#L35)

AFAIK the nuget package should have a package dependency for this specific version.

My local nuget package (using dotnet pack in the cloned repository project) has the correct dependency:

![image](https://user-images.githubusercontent.com/226753/234200489-2b5f57f6-2088-46b2-812e-4fc4507318c9.png)

But the official nuget package has a dependency for version 1.2.0.

![image](https://user-images.githubusercontent.com/226753/234202270-fb982b4b-56d5-4761-821a-609a1f71ca5c.png)

So maybe there's a problem during the build of the package (there's no public pipeline, internal process of ITG)


Thank you

**Comment by AlaaTrAce** [comment]
Hi @skeller1 ,

Thank you for bringing this to our attention.
We fixed this version conflict issue with our latest 3.2 releases! 

Best regards,
Alaa

**Comment by skeller1** [comment]
Thanks, waiting for PPJ.Web compatible release (Wisej 3.2.0) to drop our manually build package.

Issue solved
