### ISSUE TITLE
WebAuthn GetAsync should accept a List of PublicKeyCredentialDescriptors

### ISSUE THREAD

**Issue by prismamed** [iceteagroup/wisej-extensions#90]
The WebAuthn.GetAsync method should accept an Array or List of PublicKeyCredentialDescriptors.

If you have an user account with multiple registered devices you could pass all possible credential records for determining the right device.

This is the reason why "allowCredentials" of the standard expecting a array. See https://w3c.github.io/webauthn/#dom-publickeycredentialrequestoptions-allowcredentials

Now we only can pass one credential.

**Comment by LRufenacht** [comment]
Hi Daniel,

Thanks, we've updated the extension and will include the change in the next release.

You can track the status of the issue here:
https://wisej.com/issues/

Regards,
Levie

**Comment by prismamed** [comment]
Hi Levie,
Perhaps you can help me with this follow up.
I adjusted the Get method for myself  to allow multiple PublicKeyCredentialDescriptors.
The response should return the used CredentialID. So I can validate the whole process.

I see the in the javascript that you parse this information and put it into the 'attestedCredentialData' 
But my brain cannot get around with the Data. I dont know how to read the value correctly.

Please help.

Best regards
Daniel

**Comment by prismamed** [comment]
I went through the code and the webAuthn documentation (which is not very nice to read ;).
The place where you got the response from webauthn.get includes the used CredentialId. Not in the response structure but in the root of the whole repsonse object (data in the function _processResponse).

So issue solved for me and my tests. I'm looking forward to the update.

Best regards

**Comment by FrankITG** [comment]
Hi Daniel,

WebAuthn has been updated to version 3.2.4 including this enhancement.

Best regards  
Frank
