### ISSUE TITLE
Publish Wisej.Ext.PlayWright as a Nuget package

### ISSUE THREAD

**Issue by AlexandruIstrate** [iceteagroup/wisej-extensions#92]
All the other extensions are easily installable via Nuget. For Wisej.Ext.PlayWright, I literally have to copy-paste the web driver code files into my project.

Would be nice to have everything on Nuget.

Thanks!

**Comment by FrankITG** [comment]
Hi Alex,

thanks for your interest in our PlayWright Extension. It is currently still under development and we will publish it on nuget once it is not longer work in progress.

Best regards
Frank

**Comment by AlexandruIstrate** [comment]
Hi Frank,

That's great news. I'll be on the lookout for the Nuget package.

Thanks,
Alex

**Comment by AlaaTrAce** [comment]
Closing this issue for now.

**Comment by NeilHoskinsManSys** [comment]
Thanks Alaa - much appreciated

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
